version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq_inteliJ
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'  # Corrigido aqui
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   # Corrigido aqui
      - rabbitmq_log:/var/lib/rabbitmq    # Corrigido aqui

volumes:
  rabbitmq_data:  # Corrigido aqui
  rabbitmq_log:   # Corrigido aqui
